spring.application.name=auth-service
jwt.access_secret=${file:/run/secrets/jwt_access_token}
jwt.expiration-time=900000
jwt.refresh_token=${file:/run/secrets/jwt_refresh_token}
jwt.refresh-expiration-time=604800000
logging.file.name=/app/logs/app.log
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
server.port=8080
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG
